version: "2"
services:
  db:
    image: registry.openmoise.ci/moisedb:14
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/
    restart: always # run as a service
    volumes:
      - /var/lib/postgresql/data

  odoo14:
    image: odoo:14
    user: root
    depends_on:
      - db
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
    restart: always # run as a service

